astra_db:
  collection_name: "chatbotecomm"

embedding_model:
  provider: "google"
  model_name: "models/text-embedding-004"

retriever:
  top_k: 5

llm:
  provider: "google"
  model_name: "gemini-2.5-flash-preview-04-17" 